### ISSUE TITLE
the both methods have the same issue.below:

### ISSUE THREAD

**Issue by liboLiao** [dmytrodanylyk/dmytrodanylyk#7]
public synchronized SQLiteDatabase getDatabase() {
        return new mDatabaseHelper.getWritableDatabase();
    }
& 
public synchronized SQLiteDatabase openDatabase() {
       if(mOpenCounter.incrementAndGet() == 1) {
           // Opening new database
           mDatabase = mDatabaseHelper.getWritableDatabase();
       }
       return mDatabase;
   }

when u use 'openDatabase' in one thread and then 'closeDatabase' , in another thread you openDatabase, this should show exception that 'java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase'.
Think this carefully,AtomicInteger is no use.

**Comment by dmytrodanylyk** [comment]
NO all will work fine, since methods `openDatabase` and `closeDatabase` are synchronized.

Please read full article here http://www.dmytrodanylyk.com/pages/blog/concurrent-database.html
